services:
  mysql:
    container_name: gamedl_db_container
    image: mysql:latest
    ports:
      - "3306:3306"
    env_file:
      - ./env_vars
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      -  gamedl_db_files:/var/lib/mysql
volumes:
  gamedl_db_files:
